---
title: Jesus Week Waterloo
timezone: America/New_York
collections:
  connect:
    title: Connect
    output: true
    permalink: "/:collection/:name"
  events:
    title: Events
    output: true
    permalink: "/:collection/:name"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _uploads/
  values:
    sitemap: false
exclude:
- node_modules
- test-assets/node_modules
display_pages:
- about.md
- gospel.md
- events.md
- connect.md
- contact.md
baseurl: 
url: https://jesusweek.ca
future: true
logo: "/favicon.png?20190310"
encoding: utf-8
description: Choose Christ. // To make Christ known on the campuses.
plugins:
- jekyll-seo-tag
- jekyll-sitemap
