---
title: Jesus Week Waterloo
timezone: America/New_York
lang: en-ca
langs:
  en-ca: en-CA
  zh-hk: zh-yue-Hant-HK
locales:
  en-ca: en_CA
  zh-hk: zh_HK
collections:
  connect:
    title: Connect
    permalink: "/:collection/:name"
    output: true
  events:
    title: Events
    permalink: "/:collection/:name"
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ""
  values:
    lang: en-ca
- scope:
    path: _uploads/
  values:
    sitemap: false
exclude:
- node_modules
- test-assets/node_modules
display_pages:
- about.md
- gospel.md
- events.md
- connect.md
- contact.md
baseurl: 
url: "https://jesusweek.ca"
future: true
logo: "/favicon.png?20190310"
encoding: utf-8
description: "Choose Christ. // To make Christ known on the campuses."
short_description: Choose Christ.
plugins:
- jekyll-seo-tag
- jekyll-sitemap
