---
title: Jesus Week Waterloo
timezone: America/New_York
lang: en-ca
langs:
  en-ca: en-CA
  zh-hk: zh-yue-Hant-HK
locales:
  en-ca: en_CA
  zh-hk: zh_HK
collections:
  connect_en-ca:
    permalink: "/connect/:name"
    output: true
  connect_zh-hk:
    permalink: "/zh-hk/connect/:name"
    output: true
  events_en-ca:
    permalink: "/events/:name"
    output: true
  events_zh-hk:
    permalink: "/zh-hk/events/:name"
    output: true
  posts:
    output: true
  uploads:
    output: true
defaults:
- scope:
    path: ""
  values:
    lang: en-ca
- scope:
    path: _uploads/
  values:
    sitemap: false
exclude:
- node_modules
- test-assets/node_modules
baseurl: 
url: "https://jesusweek.ca"
future: true
logo: "/favicon.png?20191021"
encoding: utf-8
description: "What kind of King is this? // To make Christ known on the campuses."
short_description: What kind of King is this?
plugins:
- jekyll-seo-tag
- jekyll-sitemap
